Repository ezsystems/BehatBundle, pull requests merged in 2020-04, with the labels that each got.

#140 EZP-30543: Removed Dynamic Settings functionality from kernel
  src/bundle/Resources/config/services/fieldtype_data_providers.yaml
  src/lib/API/ContentData/FieldTypeData/ImageAssetDataProvider.php
Labels: Improvement, Ready for review

#142 Adjusted code for PHP7.4
  Context/Object/UserContext.php
Labels: Ready for review

#141 Added site/view permission to SubtreeEditor
  features/personas/subtree_editor.feature
Labels: Ready for review

#144 EZP-30465: Fixed PermissionResolver injection into Behat TestContext
  src/bundle/Resources/config/services/contexts.yaml
Labels: Ready for MERGE

#148 Adjusted Page Builder branches map for new stable branch
  Command/GetPullRequestDataCommand.php
Labels: Ready for review

#146 Moved suite name formatting to PHP code
  bin/ezreport
Labels: Ready for review

#147 [Behat] Regression script should wait for Enter when asking for confirmation
  bin/.travis/trigger_ci.sh
Labels: Ready for review
